### ISSUE TITLE
[Bug] End2End Concurrency Test Issue

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/ssi-service#302]
**Describe the bug**
End to end test is failing on the concurrency test

**To Reproduce**

Our test:
https://github.com/TBD54566975/ssi-service/blob/main/integration/credential_revocation_concurrency_integration_test.go

is failing with:
```
build-web-1         | {"level":"info","msg":"214e6a70-67fd-42b7-ab45-8841311051ab : ERROR : could not create credential: execute: failed to execute after retrying: problem with getting status list credential: only one status list credential per \u003cissuer,schema\u003e pair allowed. issuer: did:key:z6Mkqgq6tynyUAvxftZCR65exq8gzwSeKfUCDYtT4cY8FR6h schema: 72fcd4fd-3e60-4af3-af20-9b7600491f3f","time":"2023-03-01T18:46:55Z"}
```

We should never be in this state, with the watch keys watching when a status list credential gets created. 
Definitely need to debug and fix our concurrency issue here

**Comment by andresuribe87** [comment]
One issue I found is in https://github.com/TBD54566975/ssi-service/blob/4e23f84159ee2e8b2dcade77d063d10f1af24730/pkg/service/credential/service.go#L107

The function that's being called will create a new UUID when it doesn't find the corresponding StatusList in the DB. The following may happen:
1. Goroutine A calls CreateCredential. Let's call this credential X
2. A executed until after the line above. So a new ID was generated for the status list that will be created. Let's call this M.
3. Goroutine B calls CreateCredential. Let's call this credential Y.
4. B executes until after the line above. So a new ID was generated for the status list that will be created. Let's call this N. 
5. A finishes creating the credential. 
6. B finishes creating the credential.

The result of this is that `X.credential.credentialStatus.statusListCredential != Y.credential.credentialStatus.statusListCredential` (the left will be `M`, while the right one will be `N`). But that's not expected, because both credentials should use the same status list.

I'll see if I can craft a solution quickly for this.
