### ISSUE TITLE
Validate that requester has control of private key for public key passed in creation of ion did

### ISSUE THREAD

**Issue by andresuribe87** [TBD54566975/ssi-service#571]
> Would you mind explaining the rationale? Is the intention here to ensure that the requester has control of the private key associated with the public key that's being added?

Yes exactly.

> If so, is it ok to add this as a separate feature? 

Sure, let's open an issue.

_Originally posted by @decentralgabe in https://github.com/TBD54566975/ssi-service/pull/570#discussion_r1248009158_

**Comment by decentralgabe** [comment]
We would need a request-response model, where the user makes a request to add a key, we surface a nonce, and they sign over the nonce. The mechanism you describe can work, but needs the nonce - otherwise we risk replay attacks. It's not a huge threat since we're defining a custom format, but I'd argue it's better to be safe.

**Comment by andresuribe87** [comment]
Can you elaborate what the attack is stealing in this case?

The original intent of this issue is to ensure that the client has control of the private key. authn/authz of the did/ion creation endpoint are separate. So it isn't a securing mechanism, but rather it's a way to ensure that the client is passing in the correct key, and that `ssi-service` is able to understand how to validate it.

**Comment by decentralgabe** [comment]
You'd want to make sure that someone couldn't discover a signature proving they control a key and use it for another purpose than they intended, I think what you suggested is fine
